### ISSUE TITLE
[Forge 1.18.2] Datapacks not loading into worlds

### ISSUE THREAD

**Issue by Proxwian** [JTK222/Global-Packs#26]
Using [v1.12.3](https://www.curseforge.com/minecraft/mc-mods/drp-global-datapack/files/3965521) version for Forge 1.18.2

Tried to put .zip files and data folders into global_packs/required_data/ and global_packs/required_resources/, but when i create new world, data doesn't seem to be loaded into it

**Comment by davidromrell** [comment]
also having in 1.18.3 now 1.15.1

**Comment by davidromrell** [comment]
[17:39:21] [Render thread/WARN]: Missing metadata in pack optional_data
[17:39:21] [Render thread/WARN]: Missing metadata in pack required_data
[17:39:21] [Render thread/WARN]: Missing metadata in pack optional_data
[17:39:21] [Render thread/WARN]: Missing metadata in pack required_data

**Comment by davidromrell** [comment]
this can be merged with issue #28

**Comment by JTK222** [comment]
@Proxwian I'd appreciate if you could join our Discord to figure this out, otherwise it might take a while.

I'd need to know what data-/resourcepacks you're trying to use.
If it's custom ones, please make sure that they each contain a valid pack.mcmeta file at their root & for datapacks they require a data folder at their root.
For Resourcepacks an asset folder at their root.
