### ISSUE TITLE
Crash when I open the "Singleplayer" tab to create a new world.

### ISSUE THREAD

**Issue by Vinzound** [JTK222/Global-Packs#43]
I just created a new modpack with some resourcepacks that mixes Repurposed Structures and some YUNGNICKYOUNG mods, the game crashes when I go to the singleplayer menu to create a new world and it only happens when I have Global Packs activated, which is essential for that the resource packs already mentioned work correctly. I don't know what to do, here I send you the crash report...

[crash-2023-09-28_19.29.38-client.txt](https://github.com/JTK222/Global-Packs/files/12755199/crash-2023-09-28_19.29.38-client.txt)

I use the version of Forge in Minecraft 1.20.1 just in case

**Comment by JTK222** [comment]
Please provide your latest.log or if available debug.log, crashlogs rarely contain the actual reason for a crash and are imo useless garbage.
(Points at the error message at the top of the file:
`java.lang.IllegalStateException: Failed to load registries due to above errors`)

Also, please don't post a file, but use a paste site like paste.gg or https://gist.github.com/ 

Edit: Just seen you also posted this in discord, so nevermind the log part.

**Comment by Matt-ETheSilliestManAlive** [comment]
I seem to be facing the same issue specifically in 1.20.2 Fabric, with the game crashing when i try to "Create New World" in singleplayer. I am using the Feather client, but the mod has worked fine in 1.20.1, its only when trying in 1.20.2 that this crash happens.

This was my latest log i got after crashing: [(paste.gg link)](https://paste.gg/p/anonymous/8c730970e1cd4ea7805073c53029ee81)
From my perspective, lines 206-207 seems important, though I'm judging this with an untrained eye (I'm not familiar with java coding).

**Comment by JTK222** [comment]
Yours is a different issue, seems like I'll have to recall the 1.20.2 Compat and make a new build.
I am quite bussy for another week, so Idk how fast I can provide a fix.

**Comment by Vinzound** [comment]
At the moment I think it has been solved and it was a problem with other mods, sorry for the inconvenience.

**Comment by JTK222** [comment]
Original issue is now resolved, a new 1.20.2 build (v1.16.4) is released
