### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by Taknax** [JTK222/Global-Packs#7]
Very useful mod. I written a datapack with additional content for the "data" which is located at the same folder. Can this handle this automaticly too?

**Comment by JTK222** [comment]
I assume you want data & resource pack combined in one folder?
Technically it works, but it depends on your configuration.
The mod has seperate directories for resource- & datapacks.
If you want to have a shared directory, you need to change the configuration accordingly.

**Comment by Taknax** [comment]
My question was abit irritating. I have a zip file with two directories inside. "data" and "datapacks. GDR automaticlly add the "datapacks" directory in the right place. (That works so good, tanks for that)
Does GDR place the data folder too in the right place?

**Comment by JTK222** [comment]
Ah, now I understand what you want. No, that does sadly not work.
The mod does not copy any files to other places, it just tells the game to look for those files in other folders too.
Which is not really possible to do for the data folder.

I'll think about maybe adding some functionality in this way, but am not sure about it.
That's not really something datapacks should do, as this can easily corrupt your world.

**Comment by JTK222** [comment]
After a lot of consideration and seeing how confusing datapacks are already for many users, 
I am not going to add a feature for copying any files.
Otherwise people that do not understand how stuff works, would try to copy datapacks and resourcepacks, 
breaking stuff and making pack updates impossible in the future.

In general this is hard to realize, as it would make updating packs that use this feature impossible in many situations.
